---
- name: Generate JOIN Command
  shell: "kubeadm token create --print-join-command"
  register: join_command_output

- name: Generate Certificate Key
  shell: "kubeadm init phase upload-certs --upload-certs"
  register: certificate_key_output

- name: JOIN Variable
  set_fact:
    join_command: "{{ join_command_output.stdout }}" 
    certificate_key: "{{ certificate_key_output.stdout_lines[-1] }}"

- name: Create JOIN Control Plane
  shell: echo "{{ join_command }} --control-plane --certificate-key {{ certificate_key }}" > /tmp/join_control_plane

- name: Create JOIN Worker
  shell: echo "{{ join_command }}" > /tmp/join_worker

- name: Pull Commands Files
  fetch:
    src: /tmp/join_control_plane
    dest: join

- name: Pull Commands Files
  fetch:
    src: /tmp/join_worker
    dest: join
