- name: Check admin_conf
  stat:
    path: /etc/kubernetes/admin.conf
  register: __admin

- block:

  - name: initialize cluster (Flannel)
    shell: "kubeadm init --control-plane-endpoint {{ groups['domain'][0] }} --apiserver-cert-extra-sans={{ groups['domain'][0] }} --pod-network-cidr 10.244.0.0/16"
    register: result

  - name: mkdir .kube
    file:
      path: $HOME/.kube
      state: directory

  - name: copy admin_conf
    copy:
      remote_src: yes
      src: /etc/kubernetes/admin.conf
      dest: $HOME/.kube/config
      owner: root
      group: root
      mode: '600'

  when: not __admin.stat.exists

- name: Config Flannel Network
  shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml

- name: Autocompletion-1
  shell: |
    kubectl completion bash > /etc/bash_completion.d/kubectl

- name: Autocompletion-2
  shell: |
    kubeadm completion bash > /etc/bash_completion.d/kubeadm

- name: Pause for 2 Minutes to Build Pods
  ansible.builtin.pause:
    minutes: 2

