- name: Set timezone
  timezone:
    name: Etc/UTC

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}" 

- name: Add hostname to hosts (Line-1)
  lineinfile:
    path: "{{ hosts_path }}"
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 {{ inventory_hostname }}'
    owner: root
    group: root
    mode: 0644

- name: Add hostname to hosts (Line-2)
  lineinfile:
    path: "{{ hosts_path }}"
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1 {{ inventory_hostname }}'
    owner: root
    group: root
    mode: 0644

- name: Add hostname
  lineinfile:
    path: "{{ hosts_path }}"
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined  
  with_items: "{{ groups.all }}"

- name: Unlink resolv_conf
  file:
    path: "{{ resolve }}"
    state: absent

- name: Create resolv_conf
  file:
    path: "{{ resolve }}"
    state: touch

- name: Set DNS
  template:
    src: resolv.conf.j2
    dest: "{{ resolve }}"

- name: apt update
  apt:
    update_cache: yes
    
- name: install requirment package
  apt:
    name: "{{ item }}"
    state: present
    allow_downgrade: yes
  loop:
    - nload
    - iputils-ping
    - ca-certificates=20240203
    - curl=8.5.0-2ubuntu10.6
    - apt-transport-https=2.7.14build2
    - conntrack=1:1.4.8-1ubuntu1
    - gpg=2.4.4-2ubuntu17
